[project]
name = "delta-me13"
version = "0.1.0"
description = "Dataset generation pipeline for Cyrene."
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [{ name = "FelysNeko" }]
dependencies = [
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "tqdm>=4.69.1",
    "transformers>=5.14.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ruff>=0.16.0",
    "seaborn>=0.13.2",
]

[project.scripts]
delta-me13 = "pipeline.build:main"
delta-me13-unpack = "pck.unpack:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["pipeline", "pck"]

[tool.ruff]
line-length = 88
target-version = "py312"
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP"]
